import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '@/app/redux/providers'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'User Registration App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
        <footer className="absolute bottom-0 w-full text-sm text-gray-100">
          <a
            className="mx-4 hover:text-yellow-300"
            href="https://github.com/vercel/next.js/tree/canary/examples/with-redux"
          >
            github
          </a>

          <a
            className="hover:text-yellow-300"
            href="https://mq-delta.vercel.app/"
          >
            marioq
          </a>
        </footer>
      </body>
    </html>
  )
}
